// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isBrowser = typeof window !== "undefined";
const tabStorageKey = "sb-tab-id";
const tabId = isBrowser
  ? (window.sessionStorage.getItem(tabStorageKey) || (() => {
      const nextId = (typeof crypto !== "undefined" && "randomUUID" in crypto)
        ? crypto.randomUUID()
        : `tab-${Date.now()}`;
      window.sessionStorage.setItem(tabStorageKey, nextId);
      return nextId;
    })())
  : "server";

const authStorage = isBrowser
  ? {
      getItem: (key: string) => window.localStorage.getItem(`${tabId}:${key}`),
      setItem: (key: string, value: string) => window.localStorage.setItem(`${tabId}:${key}`, value),
      removeItem: (key: string) => window.localStorage.removeItem(`${tabId}:${key}`),
    }
  : undefined;

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    storageKey: `sb-${tabId}-auth-token`,
    persistSession: true,
    autoRefreshToken: true,
  },
});
